config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :users do
    get "users/profile", to: "users#profile"
  end
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :educations
  resources :favorites, only: %i[index]

  get "search", to: "pages#home_search", as: :home_search

  resources :universities, only: %i[index show] do
    resources :favorites, only: %i[create destroy]
    resources :reviews, only: %i[create index] do
      resources :votes, only: %i[create destroy]
      delete '/votes', to: 'votes#destroy'
    end
  end

  resources :reviews, only: :destroy

  resources :chatrooms, only: %i[show index create] do
    resources :messages, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :educations
  has_many :reviews
  has_many :favorites
  has_many :votes
  has_one_attached :photo
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :first_name, :last_name, presence: true

  def photo_key
    self.photo&.key.presence || 'default-avatar'
  end

  # protected

  # def confirmation_required?
  #   true
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
    @user = current_user
    @educations = @user.educations
    @universities = University.all
    @education = Education.new
  end
end

app/views/users/_add_education_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add education record</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for (education) do |f| %>
          <%= f.association :university %>
          <%= f.association :department %>
          <%= f.input :course %>
          <%= f.input_field :academic_degree, as: :select,
          collection:  ["Diploma", "Bachelor`s Degree", "Master`s Degree", "Phd"],
          # selected: 1,
          class: "form-select",
          placeholder:"Enter number of guests"  %>
          <%= f.label :academic_degree, 'Academic Degree' %>


          <div class="row">
            <div class="col">
              <%= f.input :start_date, as: :date, html5: true, :input_html => { value: Date.today} %>
            </div>

            <div class="col">
              <%= f.input :end_date, as: :date, html5: true, :input_html => { value: Date.today + 2.month} %>
            </div>
          </div>
          <%= f.input_field :university_email, class: 'form-control', placeholder: "Enter your university email" %>
          <%= f.label :university_email, 'University email' %>
          <%= f.full_error :university_email %>
          <div class="form-text">Include your university email to leave a review for your university</div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <%= f.submit 'Save', class:"btn btn-primary" %>
            <%# <button type="button" class="btn btn-primary">Save</button> %>
          </div>
        <% end %>


      </div>

    </div>
  </div>
</div>

app/views/users/_education.html.erb
<div class="row">
  <% educations.each do |education| %>
    <%= link_to university_path(education.university), class:"university-link" do %>
      <div class="d-flex my-2">
        <%= image_tag(education.university.logo, class: "uni-card-image") %>
        <div class="ms-3">
          <p class="mb-0"><strong><%= education.university.name %></strong></p>
          <div class="card-info-light">
            <p class="mb-0 text-small"><%= education.academic_degree %>, <%= education.course.name %></p>
            <p class="text-small"><%= education.start_date.strftime("%h %Y") %> - <%= education.end_date.strftime("%h %Y") %></p>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_education_modal.html.erb
<div class="modal fade" id="educationModal<%= education.id %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title my-2" id="exampleModalLabel"><strong><%= education.id.present? ? "Edit" : "Add" %> education record</strong></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= simple_form_for (education) do |f| %>
          <%= f.error_notification %>

          <% university_list = [] %>
          <% universities.each do | university | %>
            <% university_list << [university.name, university.id] %>
          <% end %>

          <% department_list = [] %>
          <% departments.each do | department | %>
            <% department_list << [department.name, department.id] %>
          <% end %>

          <% course_list = [] %>
          <% courses.each do | course | %>
            <% course_list << [course.name, course.id] %>
          <% end %>

          <div class="form-floating mb-3 mt-3">
            <%= f.input_field :university_id,
            collection: university_list,
            selected: education.university_id.presence || university_list.first.first,
            class: "form-select",
            placeholder:"Enter the name of your university"  %>
            <%= f.label :university_id, 'University name' %>
            <%= f.full_error :university_id %>
          </div>

          <div class="form-floating mb-3">
            <%= f.input_field :department_id,
            collection: department_list,
            selected: education.department_id.presence || department_list.first.first,
            class: "form-select",
            placeholder:"Enter the name of your department"  %>
            <%= f.label :department_id, 'Department name' %>
            <%= f.full_error :department_id %>
          </div>

          <div class="form-floating mb-3">
            <%= f.input_field :course_id,
            collection: course_list,
            selected: education.course_id.presence || course_list.first.first,
            class: "form-select",
            placeholder:"Enter the name of your course"  %>
            <%= f.label :course_id, 'Course name' %>
            <%= f.full_error :course_id %>
            <div class="form-text">Let us know your field of study!</div>
          </div>

          <div class="form-floating mb-3">
            <%= f.input_field :academic_degree, as: :select,
            collection:  ["Diploma", "Bachelor`s Degree", "Master`s Degree", "Phd"],
            selected: 0,
            class: "form-select",
            placeholder:"Enter number of guests"  %>
            <%= f.label :academic_degree, 'Academic Degree' %>
          </div>

          <div class= "d-flex">
            <div class="form-floating mb-3 col-6 pe-2">
              <%= f.input_field :start_date, as: :date, html5: true,
              class: "form-control",
              value: education.start_date.presence || Date.today  %>
              <%= f.label :start_date, 'Start date' %>
            </div>

            <div class="form-floating mb-3 col-6 ps-2">
              <%= f.input_field :end_date, as: :date, html5: true,
              class: "form-control",
              value: education.end_date.presence || (Date.today + 1.year)  %>
              <%= f.label :end_date, 'End date (or expected)' %>
            </div>
          </div>

          <div class="form-floating mb-4">
            <%= f.input_field :university_email, class: 'form-control', placeholder: "Enter your university email" %>
            <%= f.label :university_email, 'University email' %>
            <%= f.full_error :university_email %>
            <div class="form-text">Include your university email to leave a review for your university</div>
          </div>

          <div class="modal-footer d-flex justify-content-between">
            <% if education.id.present? %>
              <%= link_to 'Delete', education_path(education), class: "cancel-btn mx-0", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
            <% else %>
              <button type="button" class="cancel-btn mx-0" data-bs-dismiss="modal">Cancel</button>
            <% end %>
            <%= f.submit 'Save', class:"save-btn mx-0" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<div class="container mt-5 pt-3">
  <div class="d-flex">
    <div class="m-2 mt-1">
      <%= link_to :back, class: "link" do %>
        <i class="fa-solid fa-chevron-left fa-lg icon pt-3"></i>
      <% end %>
    </div>
    <h1 class="mb-4 ms-2"><strong>Profile</strong></h1>
  </div>

  <div class="margin-custom">
    <div class="d-flex justify-content-between my-2">
      <h5><strong>General details</strong></h5>
      <%= link_to edit_user_registration_path, class: "icon" do %>
        <i class="fa-solid fa-pen"></i>
      <% end %>

    </div>
    <div class="mb-3 mt-5">
      <h6 class="my-3"><strong>Profile picture</strong></h6>
      <div class="d-flex justify-content-between align-items-center">
        <%= cl_image_tag(current_user.photo_key, class: "avatar-bordered") %>
      </div>
    </div>

    <div class="row">
      <div class="col-lg-6 col-md-6 col-sm-6 col-6">
        <h6 class="my-3"><strong>First name</strong></h6>
        <%= @user.first_name %>
      </div>
      <div class="col-lg-6 col-md-6 col-sm-6 col-6">
        <h6 class="my-3"><strong>Last name</strong></h6>
        <%= @user.last_name %>
      </div>
    </div>

    <h6 class="mb-3 mt-5"><strong>Email</strong></h6>
    <%= @user.email %>

    <div class="mt-5 my-4">
      <div class="d-flex justify-content-between">
        <h5><strong>Education</strong></h5>
        <%= link_to educations_path, class: "icon" do %>
          <div>
              <i class="fa-solid fa-pen"></i>
          </div>
        <% end %>
      </div>
      <h6 class="posted-text" style="font-size: 14px;">Add your education record to leave a review for your university</h6>
    </div>
    <div>

      <% if @educations.blank? %>
        <h6>Your education record is currently empty.</h6>
      <% else %>
        <%= render "education", educations: @educations %>
      <% end %>
    </div>

  </div>
</div>