config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :users do
    get "users/profile", to: "users#profile"
  end
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :educations
  resources :favorites, only: %i[index]

  get "search", to: "pages#home_search", as: :home_search

  resources :universities, only: %i[index show] do
    resources :favorites, only: %i[create destroy]
    resources :reviews, only: %i[create index] do
      resources :votes, only: %i[create destroy]
      delete '/votes', to: 'votes#destroy'
    end
  end

  resources :reviews, only: :destroy

  resources :chatrooms, only: %i[show index create] do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 flash-index" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 flash-index" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% unless user_signed_in? %>
  <%= render "universities/signup", resource: User.new %>
<% end %>


<div class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-scroll navbar-fixed" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%# <%= image_tag "https://cdn.iconscout.com/icon/free/png-256/social-258-116292.png", height: "35px", width: "auto" %>
      <%= image_tag "updated_logo_202209xx.png", height: "auto", width: "auto"%>
      <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Universities", universities_path, class: "nav-link" %>

          </li>
          <li class="nav-item">
            <%= link_to "Channels", chatrooms_path, class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
            <%= cl_image_tag(current_user.photo_key, class: "avatar dropdown-toggle" , id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to 'My profile', users_profile_path, class: "dropdown-item" %>
              <%= link_to "My favorites", favorites_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Universities", universities_path, class: "nav-link"%>
          </li>

          <li class="nav-item">
            <a href="" data-bs-toggle="modal" data-bs-target="#staticBackdrop" class="nav-link">Sign Up</a>
            <%# <%= link_to "Log In/", user_session_path, class: "sign-up-link"%>

          </li>

        <% end %>
      </ul>
    </div>

  </div>
</div>