config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :users do
    get "users/profile", to: "users#profile"
  end
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :educations
  resources :favorites, only: %i[index]

  get "search", to: "pages#home_search", as: :home_search

  resources :universities, only: %i[index show] do
    resources :favorites, only: %i[create destroy]
    resources :reviews, only: %i[create index] do
      resources :votes, only: %i[create destroy]
      delete '/votes', to: 'votes#destroy'
    end
  end

  resources :reviews, only: :destroy

  resources :chatrooms, only: %i[show index create] do
    resources :messages, only: :create
  end
end

app/models/education.rb
class Education < ApplicationRecord
  belongs_to :university
  belongs_to :user
  belongs_to :department
  belongs_to :course

  validates :start_date, :end_date, :university_email, :academic_degree, :course, presence: true
  validates :end_date, comparison: { greater_than: :start_date }
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: %i[:edit update destroy]
  def index
    @educations = current_user.educations
    @education_new = Education.new
    @universities = University.all.order(country: :asc)
    @departments = Department.all.order(name: :asc)
    @courses = Course.all.order(name: :asc)
  end

  def new
    @education = Education.new
    @universities = University.all
  end

  def create
    @education = Education.new(education_params)
    @education.user = current_user
    if @education.save
      redirect_to users_profile_path, notice: "You have added your education record!."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @education.update(education_params)
      redirect_to educations_path, notice: "Youe education has been updated."
    else
      render :edit
    end
  end

  def destroy
    @education.destroy
    redirect_to educations_path, status: :see_other, notice: "Education record was successfully destroyed."
  end

  private

  def education_params
    params.require(:education).permit(:course, :university_id, :department_id, :academic_degree, :university_email, :start_date, :end_date)
  end

  def set_education
    @education = Education.find(params[:id])
  end
end

app/views/educations/_education_index.html.erb
<div class="row">
  <% educations.each do |education| %>
    <div class="d-flex justify-content-between align-items-start">
      <div class="d-flex my-2">
        <%= image_tag("logo.png", class: "uni-card-image") %>
        <div class="ms-3">
          <p class="mb-0"><strong><%= education.university.name %></strong></p>
          <div class="card-info-light">
            <p class="mb-0 text-small"><%= education.academic_degree %>, <%= education.course %></p>
            <p class="text-small"><%= education.start_date.strftime("%h %Y") %> - <%= education.end_date.strftime("%h %Y") %></p>
          </div>

        </div>
      </div>
      <div>
        <%= link_to edit_education_path(education), class: "link" do %>
          <i class="fa-solid fa-pen"></i>
        <% end %>

      </div>


    </div>

  <% end %>
</div>

app/views/educations/_education_list.html.erb
<div class="row">
  <% educations.each do |education| %>
    <div class="position-relative">
      <%= link_to university_path(education.university), class:"university-link" do %>
        <div class="d-flex my-2">
          <%= image_tag(education.university.logo, class: "uni-card-image") %>
          <div class="ms-3">
            <p class="mb-0"><strong><%= education.university.name %></strong></p>

            <div class="card-info-light">
              <p class="mb-0 text-small"><%= education.academic_degree %>, <%= education.course.name %></p>
              <p class="text-small"><%= education.start_date.strftime("%h %Y") %> - <%= education.end_date.strftime("%h %Y") %></p>
            </div>
          </div>
        </div>
      <% end %>
      <div style="position:absolute; top:0;right:0;">
        <i class="fa-solid fa-pen icon" data-bs-toggle="modal" data-bs-target="#educationModal<%= education.id %>"></i>
        <%= render "users/education_modal", education: education, universities: @universities, departments: @departments, courses: @courses %>
      </div>
    </div>
  <% end %>
</div>

app/views/educations/index.html.erb
<div class="container pt-4">
  <div class="d-flex justify-content-between mt-5 my-4">
    <div class="d-flex">
      <div class="m-2 back_link">
        <%= link_to users_profile_path, class: "icon" do %>
          <i class="fa-solid fa-chevron-left"></i>
        <% end %>
      </div>
      <div class="d-flex align-items-center">
        <h5 class="mb-0 ms-2"><strong>Education</strong></h5>
      </div>
    </div>

    <span class="icon">
      <i class="fa-light fa-plus fa-2x" data-bs-toggle="modal" data-bs-target="#educationModal<%= @education_new.id %>"></i>
    </span>

    <%= render "users/education_modal", education: @education_new, universities: @universities, departments: @departments, courses: @courses %>
  </div>

  <div class="margin-custom">
    <%= render "education_list", educations: @educations %>
  </div>


</div>