config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :users do
    get "users/profile", to: "users#profile"
  end
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :educations
  resources :favorites, only: %i[index]

  get "search", to: "pages#home_search", as: :home_search

  resources :universities, only: %i[index show] do
    resources :favorites, only: %i[create destroy]
    resources :reviews, only: %i[create index] do
      resources :votes, only: %i[create destroy]
      delete '/votes', to: 'votes#destroy'
    end
  end

  resources :reviews, only: :destroy

  resources :chatrooms, only: %i[show index create] do
    resources :messages, only: :create
  end
end

app/models/university.rb
class University < ApplicationRecord
  has_many :departments
  has_many :reviews, dependent: :destroy
  has_many :favorites
  has_many :educations
  has_many :courses


  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def retrieve_ratings(attr)
    total = 0
    reviews.each do |review|
      total += review.send(attr)
    end
    return 0 if reviews.count.zero?

    (total / reviews.count).to_f.round(1)
  end

  def reputability_avg
    retrieve_ratings(:reputabilty_rating)
  end

  def education_quality_avg
    retrieve_ratings(:education_quality_rating)
  end

  def campus_facilities_accom_avg
    retrieve_ratings(:campus_facilities_accom_rating)
  end

  def course_difficulty_avg
    retrieve_ratings(:course_difficulty_rating)
  end

  def social_element_avg
    retrieve_ratings(:social_element_rating)
  end

  def value_for_money_avg
    retrieve_ratings(:value_for_money_rating)
  end

  def safety_avg
    retrieve_ratings(:safety_rating)
  end

  def career_services_avg
    retrieve_ratings(:career_services_rating)
  end

  def global_avg
    stat1 = reputability_avg
    stat2 = education_quality_avg
    stat3 = campus_facilities_accom_avg
    stat4 = course_difficulty_avg
    stat5 = social_element_avg
    stat6 = value_for_money_avg
    stat7 = safety_avg
    stat8 = career_services_avg
    (stat1 + stat2 + stat3 + stat4 + stat5 + stat6 + stat7 + stat8) / 8
  end
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR country ILIKE :query OR city ILIKE :query"
      @universities = University.where(sql_query, query: "%#{params[:query]}%")
    elsif params[:country]
      @universities = University.where(country: params[:country])
    else
      @universities = University.all.order(country: :desc)
    end
  end

  def show
    set_university
    @markers = [{ lat: @university.latitude, lng: @university.longitude }]
    # @reviews = @university.reviews.order(created_at: :desc).page params[:page]
    # @reviews = @university.reviews.order(created_at: :desc).limit(2) if current_user.nil?
    @resource = User.new
    @review = Review.new
    @educations = []
    if user_signed_in?
      @can_review = current_user.educations.where(university_id: @university.id).exists?
    end
    @internal_ranking = find_ranking
    @similar_universities = University.where(country: @university.country)
    @departments = Department.all
    @rolling_admission = @university.application_deadline.nil?
  end

  private

  def set_university
    @university = University.find(params[:id])
  end

  def university_params
    params.require(:university).permit(:name,
                                       :ranking,
                                       :reviews,
                                       :description,
                                       :city,
                                       :country,
                                       :address,
                                       :student_count,
                                       :domestic_course_fee,
                                       :international_course_fee,
                                       :application_deadline,
                                       :latitude,
                                       :longitude,
                                       :logo,
                                       :image,
                                       :image2,
                                       :image3)
  end

  def find_ranking
    @all_universities = University.all
    ranked_unis = @all_universities.sort { |a, b| b.global_avg <=> a.global_avg }
    ranked_unis.find_index(@university)
  end
end

app/views/universities/_department.html.erb
  <h3 class="card-title text-center mb-3"><strong><%= department.name %></strong></h3>
  <% department.courses.each do |course| %>
    <p><%= course.name %><br></p>
  <% end %>

app/views/universities/_favorite.html.erb
<% if user_signed_in? %>
  <% favorite = current_user.favorites.find{|f| f.university == university} %>
<% end %>
<div data-controller="favorite"
     data-favorite-favorite-id-value="<%= favorite ? favorite.id : 0 %>"
     data-favorite-page-value="<%= request.path %>">

  <%= simple_form_for(:favorite, url: university_favorites_path(university.id), data: {
    action: "submit->favorite#addToFavorite",
    favorite_target: "form"
    }) do %>

    <%= button_tag type: 'submit', class: favorite_class, style: favorite_style do %>
      <i class="<%= favorite ? "fas" : "far" %> fa-heart heart-red" style="z-index: 100" data-favorite-target="heart"></i>
    <% end %>

  <% end %>
</div>

app/views/universities/_favorite_link.html.erb
<%= tag.div id: dom_id(@university), class: "container" do %>
  <% if favorite.nil? %>
    <%= link_to university_favorites_path(university_id: university.id), data: {turbo_method: :post} do %>
      <i class="fa-regular fa-heart"></i>
    <% end %>
  <% else %>
    <%= link_to favorite_path(favorite), data: {turbo_method: :delete} do %>
      <i class="fa-solid fa-heart" data-action="click->click#refresh"></i>
    <% end %>
  <% end %>
<% end %>

app/views/universities/_filtered_uni.html.erb
<div class="row">
  <% universities.each do |university| %>
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 my-4 px-3">
        <div class="card p-3 uni-index-card" >
          <strong><%= university.name  %></strong><br>
          <%= university.reviews.count %> Reviews<br>
          <%# <p><%= university.description %></p> %>
        </div>
    </div>
  <% end %>
</div>

app/views/universities/_list.html.erb
<% universities.each do |university| %>
  <%= link_to university_path(university), class:"decoration-none text-secondary" do %>
    <li class="list" data-action="click->autocomplete#select"><%= university.name %></li>
  <% end %>
<% end %>

app/views/universities/_review.html.erb
<div class="row my-2">
  <div class="col-lg-2 col-md-2 col-sm-2">
    <%= cl_image_tag(review.user.photo_key, class: "avatar") %>
    <div class="">
      <p class="mb-0 review-font"><strong><%= review.user.first_name %> <%= review.user.last_name %></strong></p>
      <div class="card-info-light review-font-small">
        <p class="mb-0"><%= education[0].course.name %></p>
        <p class=""><%= education[0].start_date.strftime("%h %Y") %> - <%= education[0].end_date.strftime("%h %Y") %></p>
      </div>
    </div>
  </div>
  <div class="col-lg-10 col-md-10 col-sm-10">
    <div class="d-flex justify-content-between mb-3">
      <div>
        <% full_stars = average_review_rating.to_i %>
        <% average_review_rating % 1 > 0 ? half_star = 1 : half_star = 0 %>
        <% empty_stars = 5 - full_stars - half_star %>

        <% full_stars.times do %>
          <i class="fa-solid fa-star star-icon"></i>
        <% end %>
        <% half_star.times do %>
          <i class="fa-solid fa-star-half-stroke star-icon"></i>
        <% end %>
        <% empty_stars.times do %>
          <i class="fa-regular fa-star star-icon"></i>
        <% end %>
      </div>

      <% if current_user == review.user %>
        <%= link_to review_path(review), class: "delete-icon py-0 px-2 mx-2", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
          <i class="fa-regular fa-trash-can"></i>
        <% end %>
      <% end %>
    </div>
    <p><%= review.comment %></p>
    <div class="d-flex justify-content-between"  data-controller="votes" data-votes-university-id-value="<%= review.university.id %>" data-votes-review-id-value="<%= review.id %>">
      <div class="d-flex justify-content-start">
        <div class="me-1">

          <%= link_to "", data: {action: current_user.nil? ? '' : 'click->votes#upvote', bs_toggle: current_user.nil? ? 'modal' : '', bs_target: current_user.nil? ? '#staticBackdrop' : ''} do %>
            <i class="fa-solid fa-thumbs-up <%= review.upvoted?(current_user)? 'upvoted' : 'unvoted' %> " data-votes-target="upvoteIcon"></i>
          <% end %>
        </div>
        <div class="me-3" data-votes-target="totalUpvote">
          <p><%= review.votes.where(status: :upvote).size %></p>
        </div>
        <div class="me-1">
          <%= link_to "", data: {action: current_user.nil? ? '' : 'click->votes#downvote', bs_toggle: current_user.nil? ? 'modal' : '', bs_target: current_user.nil? ? '#staticBackdrop' : ''} do %>
            <i class="fa-solid fa-thumbs-down <%= review.downvoted?(current_user)? 'downvoted' : 'unvoted' %>" data-votes-target="downvoteIcon"></i>
          <% end %>
        </div>
        <div data-votes-target="totalDownvote">
          <p><%= review.votes.where(status: :downvote).size %></p>
        </div>
      </div>
      <p class="posted-text">Posted on <%= review.created_at.strftime("%d %h %Y, %I:%M %P") %></p>
    </div>
  </div>
</div>

app/views/universities/_review_form.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content review-form" style="border-radius: 10px;">

      <div class="modal-body" >
        <%# <div class="review-form"> %>
          <div class="d-flex justify-content-end pt-4 pe-4">
            <button type="button" class="btn-close" data-bs-dismiss="modal" data-insert-in-list-target="close" aria-label="Close"></button>
          </div>
          <div class="review-padding my-4">
            <p class="text-green">YOUR WORDS MATTER</p>
            <h3 class = "mt-3 mb-4 text-grey"><strong>A student at this university? We would love to hear about your experience!</strong></h3>
            <%= render "reviews/form", university: @university, review: @review %>
          </div>
        <%# </div> %>
      </div>
    </div>
  </div>
</div>

app/views/universities/_signup.html.erb
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true" aria-labelledby="exampleModalToggleLabel">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div class="row">
          <div class="col-lg-7 col-md-12 col-sm-12 overflow-hidden d-none d-lg-block p-0">
            <%= image_tag "https://wallpaperaccess.com/full/6592980.jpg", style: 'max-width:110%; max-height: 100%; object-fit: contain;'%>
          </div>
          <div class="col-lg-5 col-md-12 col-sm-12 mb-5 px-5">
            <div class="d-flex justify-content-end py-4">
              <button type="button" class="btn-close" data-bs-dismiss="modal"  aria-label="Close"></button>
            </div>
            <div>
              <%# <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button> %>
              <h2 class="mb-4 signup-header-font">Join us!</h2>

              <%= simple_form_for(resource, as: :user, url: registration_path(:user),
                data: {turbo: false}) do |f| %>
                <%= f.error_notification %>

                <div class="form-floating mb-3">
                  <%= f.input_field :first_name, class: 'form-control',required: true, placeholder: "Input your first name" %>
                  <%= f.label :first_name, 'First name' %>
                  <%= f.full_error :first_name %>
                </div>

                <div class="form-floating mb-3">
                  <%= f.input_field :last_name, class: 'form-control',required: true, placeholder: "Input your last name" %>
                  <%= f.label :last_name, 'Last name' %>
                  <%= f.full_error :last_name %>
                </div>

                <div class="form-floating mb-3">
                  <%= f.input_field :email, class: 'form-control',required: true, placeholder: "Input your last name" %>
                  <%= f.label :email, 'Email' %>
                  <%= f.full_error :email %>
                </div>

                <div class="form-floating mb-3">
                  <%= f.input_field :password, class: 'form-control',required: true, placeholder: "Input your new password" %>
                  <%= f.label :password, 'Password' %>
                  <%= f.full_error :password %>
                  <div class="form-text">6 or more characters</div>
                </div>

                <div class="form-floating mb-3">
                  <%= f.input_field :password_confirmation, class: 'form-control',required: true, placeholder: "Input your new password" %>
                  <%= f.label :password_confirmation, 'Confirm password' %>
                  <%= f.full_error :password_confirmation %>
                  <div class="form-text">Retype your password</div>
                </div>

                <div class="form-actions form-btn my-4">
                  <%= f.submit "Sign up", class:"save-btn mx-0", style:"width:100%;" %>
                </div>

                <div>
                  <p class="posted-text">By signing up, you agree to receive a confirmation email from us to the email provided in the form.</p>
                </div>
              <% end %>
              <div class="d-flex justify-content-center card-info-light align-items-center">
                <p class="pe-1 text-small">Already a member?</p>
                <a href="" data-bs-target="#exampleModalToggle2" data-bs-toggle="modal" data-bs-dismiss="modal" class="sign-up-link-small">Sign in here</a>
              </div>
            </div>
          </div>

        </div>
      </div>
      <%# <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div> %>

    </div>
  </div>
</div>


<div class="modal fade" id="exampleModalToggle2" aria-hidden="true" aria-labelledby="exampleModalToggleLabel2" tabindex="-1">
  <div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-body p-0">
        <div class="row">
          <div class="col-lg-7 col-md-12 col-sm-12 overflow-hidden d-none d-lg-block p-0">
            <%= image_tag "login_form.jpg", style: 'max-width:100%; max-height: 100%; object-fit: contain;'%>
          </div>
          <div class="col-lg-5 col-md-12 col-sm-12 px-5">
            <div class="d-flex justify-content-end py-4">
              <button type="button" class="btn-close" data-bs-dismiss="modal"  aria-label="Close"></button>
            </div>
            <div class="d-flex align-items-center justify-content-center" style="height:80%;">
              <div>
                <h2 class="mb-4 signup-header-font">Welcome back!</h2>

                <%= simple_form_for(resource, as: :user, url: session_path(:user),
                  data: {turbo: false}) do |f| %>
                  <%= f.error_notification %>

                  <div class="form-floating mb-3">
                    <%= f.input_field :email, class: 'form-control',required: true, placeholder: "Input your email" %>
                    <%= f.label :email, 'Email' %>
                    <%= f.full_error :email %>
                  </div>

                  <div class="form-floating mb-3">
                    <%= f.input_field :password, class: 'form-control',required: true, placeholder: "Input your password" %>
                    <%= f.label :password, 'Password' %>
                    <%= f.full_error :password %>
                  </div>

                  <%= f.input :remember_me, as: :boolean %>

                  <div class="form-actions form-btn my-4">
                    <%= f.submit "Sign in", class:"save-btn mx-0", style:"width:100%;" %>
                  </div>
                <% end %>
                <div class="d-flex justify-content-center card-info-light mb-5">
                  <p class="pe-1 text-small">Don't have an account?</p>
                  <a href="" data-bs-target="#staticBackdrop" data-bs-toggle="modal" data-bs-dismiss="modal" class="sign-up-link-small">Sign up for free</a>
                </div>
              </div>
            </div>
          </div>

      </div>
      </div>
    </div>
  </div>
</div>

app/views/universities/_star.html.erb
<div>
  <% full_stars = @average_rating.to_i %>
  <% @average_rating % 1 > 0 ? half_star = 1 : half_star = 0 %>
  <% empty_stars = 5 - full_stars - half_star %>

  <% full_stars.times do %>
    <i class="fa-solid fa-star star-icon"></i>
  <% end %>
  <% half_star.times do %>
    <i class="fa-solid fa-star-half-stroke star-icon"></i>
  <% end %>
  <% empty_stars.times do %>
    <i class="fa-regular fa-star star-icon"></i>
  <% end %>
</div>

app/views/universities/_university.html.erb
<div class="card uni-index-card position-relative" >
  <%= link_to university_path(university), class: "home-link" do %>

    <%= image_tag university.logo, class: "logo"%>
    <p><strong><%= university.name  %></strong><br></p>
  <% end %>

  <%= render 'universities/favorite', university: university, favorite_class: "btn btn-link", favorite_style: "top:0;right:0; position:absolute;", page: "universities" %>


  <div>
    <strong><%= university.country %></strong>
  </div>
  <div class="mt-3">(Total Reviews : <%= university.reviews.count %>)</div>
  <div class="limited-text text-justify">
    <%= university.description %>
  </div>
</div>

app/views/universities/index.html.erb
<div class="container mt-5">
  <div class="row pt-4 pb-4">
    <div class="mt-4 home-form d-flex" data-controller="autocomplete" style="width: 50%; margin: 0 auto;">
      <div style="width:100%; position:relative;">
        <input data-autocomplete-target="input" search-url=<%= home_search_path %> data-action="keyup->autocomplete#update focus->autocomplete#update blur->autocomplete#clear" class="form-control" placeholder="Enter University name or Country" type="text" name="query" id="query" style="height:50px;">
        <div data-autocomplete-target="list" style="z-index: 1; position:absolute; top:38; left:0; width:100%; border-radius:5px;">

        </div>
      </div>
      <button data-action="click->autocomplete#filterUni" class="animated-border-button">Search</button>
    </div>
  </div>
  <div class="row">
    <% @universities.each do |university| %>
      <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 my-4 px-3">
        <%= render 'university', university: university %>
      </div>
    <% end %>
  </div>
</div>